# Ubuntu 18.04
dist: xenial

git:
  depth: 10

language: java

# multiple jdk version
jdk:
  - openjdk8

before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

# codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura coveralls:report
